---
- name: Prepare
  hosts: all
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: ensure https is available to apt
      when:
        - ansible_distribution in [ "Debian", "Ubuntu" ]
      apt:
        update_cache: yes
        name: apt-transport-https
        state: present
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.ca_certificates
    - role: robertdebock.microsoft_repository_keys
